### ISSUE TITLE
New bbdc website

### ISSUE THREAD

**Issue by P4pomepeii** [xplus2g4/bbdc-bot#1]
Hey! I would like to ask if you know how to code the new bbdc website. I'm having a tough time figuring it out with python and selenium as there are pseudo codes and other complicated stuff. Do you have any idea?

**Comment by xplus2g4** [comment]
This project uses pure API call, selenium not involved.
I have updated the slot finding according to the new site, auto-booking still wip

**Comment by P4pomepeii** [comment]
Hey! any updates on the auto-booking? Every time I try to install aiohttp it always gives me an error 

> WARNING: Building wheel for multidict failed: [Errno 13] Permission denied:

and 

> WARNING: Building wheel for yarl failed: [Errno 13] Permission denied:

**Comment by xplus2g4** [comment]
> Hey! any updates on the auto-booking? Every time I try to install aiohttp it always gives me an error
> 
> > WARNING: Building wheel for multidict failed: [Errno 13] Permission denied:
> 
> and
> 
> > WARNING: Building wheel for yarl failed: [Errno 13] Permission denied:

I don't think I will be implementing auto-booking any time soon.
My current workflow is: send available slots to my telegram broadcast channel. When I see a slot I wish to book, I will book manually via bbdc site.

**Comment by xplus2g4** [comment]
Auto-booking has been added. #3 
Closing this issue.

@P4pomepeii please try to install the dependencies via poetry (local deployment) or docker. I might not be able to help with dependency errors because it usually depends on your environment.
