### ISSUE TITLE
Help Needed with BBDC Bot

### ISSUE THREAD

**Issue by Silentful** [xplus2g4/bbdc-bot#2]
Hello! I have just tried running your script, I am unable to get the Telegram Bot to work, also I am unable to get any slot after an hour of running it.

In my config, I used Nov 2022 Session 1 - 9 (No slots found)

I changed the config to Mar 2023 Sessopm 1 & 2 (No slots found) But when I checked the BBDC website, it has available slots in March 2023 Session 1 & 2.

Am I able to contact you to seek your help with these matters? (Telegram or Email)

Thank you.

**Comment by xplus2g4** [comment]
Please post your config file here. (censor your username, password and telegram related info)

**Comment by xplus2g4** [comment]
> Hello! I have just tried running your script, I am unable to get the Telegram Bot to work, also I am unable to get any slot after an hour of running it.
> 
> In my config, I used Nov 2022 Session 1 - 9 (No slots found)
> 
> I changed the config to Mar 2023 Sessopm 1 & 2 (No slots found) But when I checked the BBDC website, it has available slots in March 2023 Session 1 & 2.
> 
> Am I able to contact you to seek your help with these matters? (Telegram or Email)
> 
> Thank you.

Please post your config file here. (censor your username, password and telegram related info)

**Comment by Silentful** [comment]
> > Hello! I have just tried running your script, I am unable to get the Telegram Bot to work, also I am unable to get any slot after an hour of running it.
> > In my config, I used Nov 2022 Session 1 - 9 (No slots found)
> > I changed the config to Mar 2023 Sessopm 1 & 2 (No slots found) But when I checked the BBDC website, it has available slots in March 2023 Session 1 & 2.
> > Am I able to contact you to seek your help with these matters? (Telegram or Email)
> > Thank you.
> 
> Please post your config file here. (censor your username, password and telegram related info)

![image](https://user-images.githubusercontent.com/118662597/202900322-510e7acb-578c-4924-9b23-373db3ba27a1.png)

**Comment by Silentful** [comment]
> > Hello! I have just tried running your script, I am unable to get the Telegram Bot to work, also I am unable to get any slot after an hour of running it.
> > In my config, I used Nov 2022 Session 1 - 9 (No slots found)
> > I changed the config to Mar 2023 Sessopm 1 & 2 (No slots found) But when I checked the BBDC website, it has available slots in March 2023 Session 1 & 2.
> > Am I able to contact you to seek your help with these matters? (Telegram or Email)
> > Thank you.
> 
> Please post your config file here. (censor your username, password and telegram related info)

![image](https://user-images.githubusercontent.com/118662597/202900358-c7c22033-3654-4908-a9ec-a0b303a7d8eb.png)

**Comment by xplus2g4** [comment]
> > > Hello! I have just tried running your script, I am unable to get the Telegram Bot to work, also I am unable to get any slot after an hour of running it.
> > > In my config, I used Nov 2022 Session 1 - 9 (No slots found)
> > > I changed the config to Mar 2023 Sessopm 1 & 2 (No slots found) But when I checked the BBDC website, it has available slots in March 2023 Session 1 & 2.
> > > Am I able to contact you to seek your help with these matters? (Telegram or Email)
> > > Thank you.
> > 
> > 
> > Please post your config file here. (censor your username, password and telegram related info)
> 
> ![image](https://user-images.githubusercontent.com/118662597/202900358-c7c22033-3654-4908-a9ec-a0b303a7d8eb.png)

I just updated master, please pull. Remember to change your want_months that you wish to book, you can test with `202303`.

Also please avoid using 1 min interval, your account might get blacklisted for about 1 day. You can add more accounts under `accounts` section in config to avoid the rate-limit

**Comment by Silentful** [comment]
> > > > Hello! I have just tried running your script, I am unable to get the Telegram Bot to work, also I am unable to get any slot after an hour of running it.
> > > > In my config, I used Nov 2022 Session 1 - 9 (No slots found)
> > > > I changed the config to Mar 2023 Sessopm 1 & 2 (No slots found) But when I checked the BBDC website, it has available slots in March 2023 Session 1 & 2.
> > > > Am I able to contact you to seek your help with these matters? (Telegram or Email)
> > > > Thank you.
> > > 
> > > 
> > > Please post your config file here. (censor your username, password and telegram related info)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/118662597/202900358-c7c22033-3654-4908-a9ec-a0b303a7d8eb.png)
> 
> I just updated master, please pull. Remember to change your want_months that you wish to book, you can test with `202303`.
> 
> Also please avoid using 1 min interval, your account might get blacklisted for about 1 day. You can add more accounts under `accounts` section in config to avoid the rate-limit

Hi, noted the changes, I will try again tomorrow. Can I check what would be a recommended interval? Is 5 Minute Interval okay? Also regarding the issue where the telegram bot does not send anything, was it an issue in the code, or did I set up the config wrongly? Also just to confirm, you recently removed the variable to pick specific dates as well right? now can only pick Month and Session.

Thank you.

**Comment by xplus2g4** [comment]
@Silentful 

> Can I check what would be a recommended interval?

For single account, I would recommend 50 minute interval. You may reduce the interval time if you are adding more accounts (e.g. from your friends).

> the issue where the telegram bot does not send anything

I don't see any issue in the code. You can test it via `python -m bbdc-bot.telegram`. You should receive a message from the bot if you configure it correctly. When you run the script, the bot will only notify you if it finds a slot.

> removed the variable to pick specific dates

Yes I removed that because I don't really use that feature. As explained earlier, I manually choose and book the slots that the bot sent me. From experience, you will find people cancelling their slots one day before their lesson. You can make changes to the code according to your need.

**Comment by xplus2g4** [comment]
Auto-booking is now supported #3 

@Silentful You can now pick specific dates under account config, the bot will auto booking the slots for you.
If you don't have any other questions, I will proceed with closing the issue.

**Comment by Silentful** [comment]
> Auto-booking is now supported #3
> 
> @Silentful You can now pick specific dates under account config, the bot will auto booking the slots for you. If you don't have any other questions, I will proceed with closing the issue.

Hi @xplus2g4 ,

![image](https://user-images.githubusercontent.com/118662597/203288427-cf1bb866-8cad-4286-a11f-6b25ca854475.png)

I tried running again and found that the issue is that my BBDC account is enrolled in both 2B and 3C. I suspect it is not working as it is entering my 2B account which I have graduated from and does not have available practical slots or balance in it. I tried the script with another friend's account which only has 3C enrolled and it worked. Do you have a solution to this issue.

Thank you.
